[package]
name = "nesquick"
version = "0.1.0"
authors = ["Arthur Cros <cros_b@etna-alternance.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
